name = "baseline-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ALLOWED_ORIGIN = "https://andrewdeal.info"

[[kv_namespaces]]
binding = "LOGS"
id = "8818d789085540ee80b0cc8448ce1113"
